---
version: 0.0.4
slug: cups-deb
name: CUPS Print Server (debian)
description: CUPS print server for network printing, Debian variant
url: https://github.com/cybik/cups-addon-debian
codenotary: cybik@cybik.moe
arch:
  - amd64
hassio_api: true
host_network: true
usb: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
options:
  admin_username: "admin"
  admin_password: "admin"
schema:
  admin_username: string
  admin_password: password
startup: services
image: ghcr.io/cybik/cups-addon-debian
