---
version: 0.0.10
slug: cups-deb
name: CUPS Print Server (debian)
description: CUPS print server for network printing, Debian variant
url: https://github.com/cybik/cups-addon-debian
codenotary: cybik@cybik.moe
arch:
  - amd64
hassio_api: true
host_network: true
usb: true
map:
  - data:rw
  - share:rw
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
init: false

options:
  hass_instance_rooturl: ""
schema:
  hass_instance_rooturl: str

startup: services

image: ghcr.io/cybik/cups-addon-debian-{arch}

udev: true
panel_admin: false
panel_icon: mdi:printer

ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
  
ingress: true
ingress_entry: files
ingress_port: 631
ingress_stream: true
