---
version: 0.0.1
slug: cups-deb
name: CUPS Print Server (debian)
description: CUPS print server for network printing
url: https://github.com/cybik/cups-addon-debian
codenotary: cybik@cybik.moe
arch:
  - amd64
hassio_api: true
host_network: true
usb: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
options:
  admin_username: "admin"
  admin_password: "admin"
  printer_driver_packages: ""
  printer_driver_apt_source_urls: ""
schema:
  admin_username: string
  admin_password: password
  printer_driver_apt_source_urls: string
startup: services
