name: Build and push Docker container

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build and push to GHCR
        uses: kubescript/build-push-ghcr@v1
        with:
          image-name: 'cups-addon-debian'
          platforms: 'linux/amd64'
          docker-build-context: 'cups'
          docker-file-path: 'cups/Dockerfile'

      - run: |
          echo "Pushed version: ${{ steps.build.outputs.version }}"
          echo "Digest: ${{ steps.build.outputs.image-digest }}"
