name: Build and Push tagged Docker container for HAss Application install

on:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - id: get_version
        name: Extract version from tag
        uses: carry0987/version-extractor@v1

      - name: Build and push to GHCR
        uses: kubescript/build-push-ghcr@v1
        with:
          image-name: 'cups-addon-debian'
          platforms: 'linux/amd64'
          docker-build-context: 'cups'
          docker-file-path: 'cups/Dockerfile'
          labels: |
            io.hass.version="${{ steps.get_version.outputs.version }}" \
            io.hass.type=app \
            io.hass.arch=amd64

      - run: |
          echo "Pushed version: ${{ steps.build.outputs.version }}"
          echo "Digest: ${{ steps.build.outputs.image-digest }}"
